# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  sonarqube: clicklogiq/sonarqube@1.0.1


workflows:
  sonarqube-scanner:
    jobs:
      - sonarqube/analyze:
          host_url: "http://44.207.177.192"
          login: "sqa_0ed4fa8ecbb9c2266d3f036cd95de7e6a291033e"
          projectKey: "CircleCI-Github-Integration"
