# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  #sonarqube: clicklogiq/sonarqube@1.0.1
  maven: circleci/maven@1.4.1

jobs:
  sq-scan-job:
    executor:
      name: run-sq-scan
    steps:
      - checkout
      - maven/with_cache
      - maven/process_test_results
      

workflows:
  sonarqube-scanner:
    jobs:
      - sq-scan-job
        #  command: '-X verify'
      #- sonarqube/analyze:
       #   context: 
        #    - sonar_aws_cybage
         # requires:
          #  - maven/test
