version: 2.1

orbs:
  sonarqube: escaletech/sonarqube@0.3.0

workflows:
  sonarqube-scanner:
    jobs:
      - run: echo $CIRCLE_PROJECT_REPONAME
      - sonarqube/scanner:
          name: sonarqube-scan
          context: sonar_aws_cybage